### ISSUE TITLE
feat(patch): New switch for autoplay/repeat option.

### ISSUE THREAD

**Issue by danieloox** [inotia00/revanced-patches#40]
### Application

YouTube.

### Issue

There are currently two options, (autoplay and always autorepeat), which do not work properly on off screen when both enabled (always auto-repeat does not work).

### Patch

Make a triple switch if possible :
0 tap -all options off.
1 tap- autoplay on.
2 tap- autoplay off and always autorepeat on.
3 tap- back to 0 (always autorepeat off)
and again.
Setting should be remembered and work in every video even after restarting the application. (as always autorepeat now).

### Motivation

One better option instead of two.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Now it is clear. I can only guess what could be the cause. (although not 100% sure)
I will mention you again when the issue is resolved.

**Comment by inotia00** [comment]
The issue should have been fixed in revanced-patches v2.99.0. (maybe..)

The parts I solved are:

1. AutoPlay setting is turned on. (YouTube settings)
2. The AutoRepeat setting is turned on. (Revanced settings)
3. Video ends with screen off

Fixed an issue where autorepeat did not work in this situation.

Please test with revanced-patches v2.99.0 and close if the issue is resolved.

**Comment by danieloox** [comment]
I tested it a bit. Yes, it's wonderful now. Well done.
